/*********************************************************************
 * File Name: http_print.c
 *
 * Provides callback headers and resolution for user's custom
 * HTTP Application.
 * 
 * This file is automatically generated by the MPFS Utility
 * ALL MODIFICATIONS WILL BE OVERWRITTEN BY THE MPFS GENERATOR
 *
 * Software License Agreement
 *
 * Copyright (C) 2012 Microchip Technology Inc.  All rights
 * reserved.
 * Microchip licenses to you the right to use, modify, copy, and distribute
 * software only embedded on a Microchip microcontroller or digital signal 
 * controller that is integrated into your product or third party product
 * (pursuant to the sublicense terms in the accompanying license agreement)

 * You should refer to the license agreement accompanying this 
 * Software for additional information regarding your rights and 
 * obligations.
 *
 * You should refer to the license agreement accompanying this 
 * Software for additional information regarding your rights and 
 * obligations.
 *
 * THE SOFTWARE AND DOCUMENTATION ARE PROVIDED "AS IS" WITHOUT
 * WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT
 * LIMITATION, ANY WARRANTY OF MERCHANTABILITY, FITNESS FOR A 
 * PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL
 * MICROCHIP BE LIABLE FOR ANY INCIDENTAL, SPECIAL, INDIRECT OR
 * CONSEQUENTIAL DAMAGES, LOST PROFITS OR LOST DATA, COST OF
 * PROCUREMENT OF SUBSTITUTE GOODS, TECHNOLOGY OR SERVICES, ANY CLAIMS
 * BY THIRD PARTIES (INCLUDING BUT NOT LIMITED TO ANY DEFENSE 
 * THEREOF), ANY CLAIMS FOR INDEMNITY OR CONTRIBUTION, OR OTHER 
 * SIMILAR COSTS, WHETHER ASSERTED ON THE BASIS OF CONTRACT, TORT
 * (INCLUDING NEGLIGENCE), BREACH OF WARRANTY, OR OTHERWISE.
 *
 *********************************************************************/

#include "tcpip/tcpip.h"

void TCPIP_HTTP_Print(HTTP_CONN_HANDLE connHandle,uint32_t callbackID);
void TCPIP_HTTP_Print_hellomsg(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_cookiename(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_led(HTTP_CONN_HANDLE connHandle,uint16_t);
void TCPIP_HTTP_Print_nextSSID(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_prevSSID(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_prevWLAN(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_nextWLAN(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_uploadedmd5(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_scan(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_fwver(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_bssCount(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_ssid(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_valid(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_name(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_privacy(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_wlan(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_strength(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_snmp_en(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_read_comm(HTTP_CONN_HANDLE connHandle,uint16_t);
void TCPIP_HTTP_Print_write_comm(HTTP_CONN_HANDLE connHandle,uint16_t);
void TCPIP_HTTP_Print_status_fail(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_config_mac(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_config_hostname(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_config_dhcpchecked(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_config_ip(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_config_gw(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_config_subnet(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_config_dns1(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_config_dns2(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_reboot(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_rebootaddr(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_status_ok(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_smtps_en(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_ddns_status(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_ddns_status_msg(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_ddns_service(HTTP_CONN_HANDLE connHandle,uint16_t);
void TCPIP_HTTP_Print_ddns_user(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_ddns_pass(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_ddns_host(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_remoteServer(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_uuid(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_show_dc(HTTP_CONN_HANDLE connHandle,uint16_t);
void TCPIP_HTTP_Print_show_co(HTTP_CONN_HANDLE connHandle,uint16_t);
void TCPIP_HTTP_Print_show_door(HTTP_CONN_HANDLE connHandle,uint16_t);
void TCPIP_HTTP_Print_humidTh(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_lightTh(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_batteryTh(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_sensor_adc(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_adc_pir(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_tprTh(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_waterTh(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_adcTh(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_curTh(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_dry(HTTP_CONN_HANDLE connHandle,uint16_t);
void TCPIP_HTTP_Print_vdc_input(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_batt0(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_temp(HTTP_CONN_HANDLE connHandle,uint16_t);
void TCPIP_HTTP_Print_humid0(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_water0(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_light0(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_adc0(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_cur0(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_date(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_time(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_chg_status(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_vbatt(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_ichg(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_rlysw(HTTP_CONN_HANDLE connHandle,uint16_t);
void TCPIP_HTTP_Print_gmt_time(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_ntp_checked(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_config_port(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_androidport(HTTP_CONN_HANDLE connHandle,uint16_t);
void TCPIP_HTTP_Print_cookieven(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_cookieddns(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_cookiemail(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_config_usr(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_config_pass(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_config_humidchecked(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_HumidAlmType(HTTP_CONN_HANDLE connHandle,uint16_t);
void TCPIP_HTTP_Print_config_curchecked(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_CurAlmType(HTTP_CONN_HANDLE connHandle,uint16_t);
void TCPIP_HTTP_Print_config_lightchecked(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_LightAlmType1(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_LightAlmType2(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_LightAlmType3(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_dcinTh(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_config_dcinchecked(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_DCMainAlmType(HTTP_CONN_HANDLE connHandle,uint16_t);
void TCPIP_HTTP_Print_config_battchecked(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_BattAlmType(HTTP_CONN_HANDLE connHandle,uint16_t);
void TCPIP_HTTP_Print_bckbatteryTh(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_config_bckbattchecked(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_BckBattAlmType(HTTP_CONN_HANDLE connHandle,uint16_t);
void TCPIP_HTTP_Print_config_tprchecked(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_TprAlmType(HTTP_CONN_HANDLE connHandle,uint16_t);
void TCPIP_HTTP_Print_config_waterchecked(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_WtrAlmType(HTTP_CONN_HANDLE connHandle,uint16_t);
void TCPIP_HTTP_Print_config_adcchecked(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_ADCAlmType(HTTP_CONN_HANDLE connHandle,uint16_t);
void TCPIP_HTTP_Print_ADCSensorNone(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_ADCSensorPIR(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_config_drychecked(HTTP_CONN_HANDLE connHandle,uint16_t);
void TCPIP_HTTP_Print_Dry1AlmType1(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_Dry1AlmType2(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_notify_dry_clear(HTTP_CONN_HANDLE connHandle,uint16_t);
void TCPIP_HTTP_Print_Dry1Sensor(HTTP_CONN_HANDLE connHandle,uint16_t);
void TCPIP_HTTP_Print_Dry2AlmType1(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_Dry2AlmType2(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_Dry2Sensor(HTTP_CONN_HANDLE connHandle,uint16_t);
void TCPIP_HTTP_Print_Dry3AlmType1(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_Dry3AlmType2(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_Dry3Sensor(HTTP_CONN_HANDLE connHandle,uint16_t);
void TCPIP_HTTP_Print_Dry4AlmType1(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_Dry4AlmType2(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_Dry4Sensor(HTTP_CONN_HANDLE connHandle,uint16_t);
void TCPIP_HTTP_Print_status_ip(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_Public_IPAddress(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_new_wanip(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_old_wanip(HTTP_CONN_HANDLE connHandle);

void TCPIP_HTTP_Print(HTTP_CONN_HANDLE connHandle,uint32_t callbackID)
{
TCP_SOCKET sktHTTP; 
	switch(callbackID)
	{
        case 0x00000000:
			TCPIP_HTTP_FileInclude(connHandle,(const uint8_t*)"header.inc");
			break;
        case 0x00000001:
			TCPIP_HTTP_Print_hellomsg(connHandle);
			break;
        case 0x00000002:
			TCPIP_HTTP_FileInclude(connHandle,(const uint8_t*)"footer.inc");
			break;
        case 0x00000003:
			TCPIP_HTTP_Print_cookiename(connHandle);
			break;
        case 0x00000007:
			TCPIP_HTTP_Print_led(connHandle,2);
			break;
        case 0x00000008:
			TCPIP_HTTP_Print_led(connHandle,1);
			break;
        case 0x00000010:
			TCPIP_HTTP_Print_led(connHandle,0);
			break;
        case 0x00000011:
			TCPIP_HTTP_Print_nextSSID(connHandle);
			break;
        case 0x00000012:
			TCPIP_HTTP_Print_prevSSID(connHandle);
			break;
        case 0x00000013:
			TCPIP_HTTP_Print_prevWLAN(connHandle);
			break;
        case 0x00000014:
			TCPIP_HTTP_Print_nextWLAN(connHandle);
			break;
        case 0x00000019:
			TCPIP_HTTP_Print_uploadedmd5(connHandle);
			break;
        case 0x0000001a:
			TCPIP_HTTP_Print_scan(connHandle);
			break;
        case 0x0000001b:
			TCPIP_HTTP_Print_fwver(connHandle);
			break;
        case 0x0000001c:
			TCPIP_HTTP_Print_bssCount(connHandle);
			break;
        case 0x0000001d:
			TCPIP_HTTP_Print_ssid(connHandle);
			break;
        case 0x0000001e:
			TCPIP_HTTP_Print_valid(connHandle);
			break;
        case 0x0000001f:
			TCPIP_HTTP_Print_name(connHandle);
			break;
        case 0x00000020:
			TCPIP_HTTP_Print_privacy(connHandle);
			break;
        case 0x00000021:
			TCPIP_HTTP_Print_wlan(connHandle);
			break;
        case 0x00000022:
			TCPIP_HTTP_Print_strength(connHandle);
			break;
        case 0x00000023:
			TCPIP_HTTP_Print_snmp_en(connHandle);
			break;
        case 0x00000024:
			TCPIP_HTTP_Print_read_comm(connHandle,0);
			break;
        case 0x00000025:
			TCPIP_HTTP_Print_read_comm(connHandle,1);
			break;
        case 0x00000026:
			TCPIP_HTTP_Print_read_comm(connHandle,2);
			break;
        case 0x00000027:
			TCPIP_HTTP_Print_write_comm(connHandle,0);
			break;
        case 0x00000028:
			TCPIP_HTTP_Print_write_comm(connHandle,1);
			break;
        case 0x00000029:
			TCPIP_HTTP_Print_write_comm(connHandle,2);
			break;
        case 0x0000002a:
			TCPIP_HTTP_Print_status_fail(connHandle);
			break;
        case 0x0000002b:
			TCPIP_HTTP_Print_config_mac(connHandle);
			break;
        case 0x0000002c:
			TCPIP_HTTP_Print_config_hostname(connHandle);
			break;
        case 0x0000002d:
			TCPIP_HTTP_Print_config_dhcpchecked(connHandle);
			break;
        case 0x0000002e:
			TCPIP_HTTP_Print_config_ip(connHandle);
			break;
        case 0x0000002f:
			TCPIP_HTTP_Print_config_gw(connHandle);
			break;
        case 0x00000030:
			TCPIP_HTTP_Print_config_subnet(connHandle);
			break;
        case 0x00000031:
			TCPIP_HTTP_Print_config_dns1(connHandle);
			break;
        case 0x00000032:
			TCPIP_HTTP_Print_config_dns2(connHandle);
			break;
        case 0x00000033:
			TCPIP_HTTP_Print_reboot(connHandle);
			break;
        case 0x00000034:
			TCPIP_HTTP_Print_rebootaddr(connHandle);
			break;
        case 0x00000035:
			TCPIP_HTTP_Print_status_ok(connHandle);
			break;
        case 0x00000036:
			TCPIP_HTTP_Print_smtps_en(connHandle);
			break;
        case 0x00000037:
			TCPIP_HTTP_Print_ddns_status(connHandle);
			break;
        case 0x00000038:
			TCPIP_HTTP_Print_ddns_status_msg(connHandle);
			break;
        case 0x00000039:
			TCPIP_HTTP_Print_ddns_service(connHandle,0);
			break;
        case 0x0000003a:
			TCPIP_HTTP_Print_ddns_service(connHandle,1);
			break;
        case 0x0000003b:
			TCPIP_HTTP_Print_ddns_service(connHandle,2);
			break;
        case 0x0000003c:
			TCPIP_HTTP_Print_ddns_user(connHandle);
			break;
        case 0x0000003d:
			TCPIP_HTTP_Print_ddns_pass(connHandle);
			break;
        case 0x0000003e:
			TCPIP_HTTP_Print_ddns_host(connHandle);
			break;
        case 0x0000003f:
			TCPIP_HTTP_Print_remoteServer(connHandle);
			break;
        case 0x00000040:
			TCPIP_HTTP_Print_uuid(connHandle);
			break;
        case 0x00000041:
			TCPIP_HTTP_Print_show_dc(connHandle,0);
			break;
        case 0x00000042:
			TCPIP_HTTP_Print_show_co(connHandle,0);
			break;
        case 0x00000043:
			TCPIP_HTTP_Print_show_door(connHandle,0);
			break;
        case 0x00000044:
			TCPIP_HTTP_Print_show_dc(connHandle,1);
			break;
        case 0x00000045:
			TCPIP_HTTP_Print_show_co(connHandle,1);
			break;
        case 0x00000046:
			TCPIP_HTTP_Print_show_door(connHandle,1);
			break;
        case 0x00000047:
			TCPIP_HTTP_Print_show_dc(connHandle,2);
			break;
        case 0x00000048:
			TCPIP_HTTP_Print_show_co(connHandle,2);
			break;
        case 0x00000049:
			TCPIP_HTTP_Print_show_door(connHandle,2);
			break;
        case 0x0000004a:
			TCPIP_HTTP_Print_show_dc(connHandle,3);
			break;
        case 0x0000004b:
			TCPIP_HTTP_Print_show_co(connHandle,3);
			break;
        case 0x0000004c:
			TCPIP_HTTP_Print_show_door(connHandle,3);
			break;
        case 0x0000004d:
			TCPIP_HTTP_Print_humidTh(connHandle);
			break;
        case 0x0000004e:
			TCPIP_HTTP_Print_lightTh(connHandle);
			break;
        case 0x0000004f:
			TCPIP_HTTP_Print_batteryTh(connHandle);
			break;
        case 0x00000050:
			TCPIP_HTTP_Print_sensor_adc(connHandle);
			break;
        case 0x00000051:
			TCPIP_HTTP_Print_adc_pir(connHandle);
			break;
        case 0x00000052:
			TCPIP_HTTP_Print_tprTh(connHandle);
			break;
        case 0x00000053:
			TCPIP_HTTP_Print_waterTh(connHandle);
			break;
        case 0x00000054:
			TCPIP_HTTP_Print_adcTh(connHandle);
			break;
        case 0x00000055:
			TCPIP_HTTP_Print_curTh(connHandle);
			break;
        case 0x00000089:
			TCPIP_HTTP_Print_led(connHandle,3);
			break;
        case 0x0000008a:
			TCPIP_HTTP_Print_led(connHandle,4);
			break;
        case 0x0000008b:
			TCPIP_HTTP_Print_led(connHandle,5);
			break;
        case 0x0000008c:
			TCPIP_HTTP_Print_led(connHandle,6);
			break;
        case 0x0000008d:
			TCPIP_HTTP_Print_led(connHandle,7);
			break;
        case 0x0000008e:
			TCPIP_HTTP_Print_led(connHandle,8);
			break;
        case 0x0000008f:
			TCPIP_HTTP_Print_led(connHandle,9);
			break;
        case 0x00000090:
			TCPIP_HTTP_Print_led(connHandle,10);
			break;
        case 0x00000091:
			TCPIP_HTTP_Print_led(connHandle,11);
			break;
        case 0x00000092:
			TCPIP_HTTP_Print_led(connHandle,12);
			break;
        case 0x00000093:
			TCPIP_HTTP_Print_led(connHandle,13);
			break;
        case 0x00000094:
			TCPIP_HTTP_Print_led(connHandle,14);
			break;
        case 0x00000096:
			TCPIP_HTTP_Print_dry(connHandle,0);
			break;
        case 0x00000097:
			TCPIP_HTTP_Print_dry(connHandle,1);
			break;
        case 0x00000098:
			TCPIP_HTTP_Print_dry(connHandle,2);
			break;
        case 0x00000099:
			TCPIP_HTTP_Print_dry(connHandle,3);
			break;
        case 0x0000009a:
			TCPIP_HTTP_Print_vdc_input(connHandle);
			break;
        case 0x0000009b:
			TCPIP_HTTP_Print_batt0(connHandle);
			break;
        case 0x0000009c:
			TCPIP_HTTP_Print_temp(connHandle,0);
			break;
        case 0x0000009d:
			TCPIP_HTTP_Print_temp(connHandle,1);
			break;
        case 0x0000009e:
			TCPIP_HTTP_Print_humid0(connHandle);
			break;
        case 0x0000009f:
			TCPIP_HTTP_Print_water0(connHandle);
			break;
        case 0x000000a0:
			TCPIP_HTTP_Print_light0(connHandle);
			break;
        case 0x000000a1:
			TCPIP_HTTP_Print_adc0(connHandle);
			break;
        case 0x000000a2:
			TCPIP_HTTP_Print_cur0(connHandle);
			break;
        case 0x000000a3:
			TCPIP_HTTP_Print_date(connHandle);
			break;
        case 0x000000a4:
			TCPIP_HTTP_Print_time(connHandle);
			break;
        case 0x000000a5:
			TCPIP_HTTP_Print_chg_status(connHandle);
			break;
        case 0x000000a6:
			TCPIP_HTTP_Print_vbatt(connHandle);
			break;
        case 0x000000a7:
			TCPIP_HTTP_Print_ichg(connHandle);
			break;
        case 0x000000a8:
			TCPIP_HTTP_Print_rlysw(connHandle,1);
			break;
        case 0x000000a9:
			TCPIP_HTTP_Print_rlysw(connHandle,2);
			break;
        case 0x000000aa:
			TCPIP_HTTP_Print_gmt_time(connHandle);
			break;
        case 0x000000ab:
			TCPIP_HTTP_Print_ntp_checked(connHandle);
			break;
        case 0x000000ae:
			TCPIP_HTTP_Print_config_port(connHandle);
			break;
        case 0x000000af:
			TCPIP_HTTP_Print_androidport(connHandle,5000);
			break;
        case 0x000000b0:
			TCPIP_HTTP_Print_androidport(connHandle,5001);
			break;
        case 0x000000b1:
			TCPIP_HTTP_Print_androidport(connHandle,5002);
			break;
        case 0x000000b2:
			TCPIP_HTTP_Print_androidport(connHandle,5003);
			break;
        case 0x000000b3:
			TCPIP_HTTP_Print_androidport(connHandle,5004);
			break;
        case 0x000000b4:
			TCPIP_HTTP_Print_androidport(connHandle,5005);
			break;
        case 0x000000b5:
			TCPIP_HTTP_Print_androidport(connHandle,5006);
			break;
        case 0x000000b6:
			TCPIP_HTTP_Print_androidport(connHandle,5007);
			break;
        case 0x000000b7:
			TCPIP_HTTP_Print_androidport(connHandle,5008);
			break;
        case 0x000000b8:
			TCPIP_HTTP_Print_androidport(connHandle,5009);
			break;
        case 0x000000bc:
			TCPIP_HTTP_Print_cookieven(connHandle);
			break;
        case 0x000000bd:
			TCPIP_HTTP_Print_cookieddns(connHandle);
			break;
        case 0x000000be:
			TCPIP_HTTP_Print_cookiemail(connHandle);
			break;
        case 0x000000bf:
			TCPIP_HTTP_Print_config_usr(connHandle);
			break;
        case 0x000000c0:
			TCPIP_HTTP_Print_config_pass(connHandle);
			break;
        case 0x000000c3:
			TCPIP_HTTP_Print_config_humidchecked(connHandle);
			break;
        case 0x000000c4:
			TCPIP_HTTP_Print_HumidAlmType(connHandle,1);
			break;
        case 0x000000c5:
			TCPIP_HTTP_Print_HumidAlmType(connHandle,2);
			break;
        case 0x000000c6:
			TCPIP_HTTP_Print_HumidAlmType(connHandle,3);
			break;
        case 0x000000d0:
			TCPIP_HTTP_Print_config_curchecked(connHandle);
			break;
        case 0x000000d1:
			TCPIP_HTTP_Print_CurAlmType(connHandle,1);
			break;
        case 0x000000d2:
			TCPIP_HTTP_Print_CurAlmType(connHandle,2);
			break;
        case 0x000000d3:
			TCPIP_HTTP_Print_CurAlmType(connHandle,3);
			break;
        case 0x000000dd:
			TCPIP_HTTP_Print_config_lightchecked(connHandle);
			break;
        case 0x000000de:
			TCPIP_HTTP_Print_LightAlmType1(connHandle);
			break;
        case 0x000000df:
			TCPIP_HTTP_Print_LightAlmType2(connHandle);
			break;
        case 0x000000e0:
			TCPIP_HTTP_Print_LightAlmType3(connHandle);
			break;
        case 0x000000ea:
			TCPIP_HTTP_Print_dcinTh(connHandle);
			break;
        case 0x000000eb:
			TCPIP_HTTP_Print_config_dcinchecked(connHandle);
			break;
        case 0x000000ec:
			TCPIP_HTTP_Print_DCMainAlmType(connHandle,1);
			break;
        case 0x000000ed:
			TCPIP_HTTP_Print_DCMainAlmType(connHandle,2);
			break;
        case 0x000000ee:
			TCPIP_HTTP_Print_DCMainAlmType(connHandle,3);
			break;
        case 0x000000ef:
			TCPIP_HTTP_Print_config_battchecked(connHandle);
			break;
        case 0x000000f0:
			TCPIP_HTTP_Print_BattAlmType(connHandle,1);
			break;
        case 0x000000f1:
			TCPIP_HTTP_Print_BattAlmType(connHandle,2);
			break;
        case 0x000000f2:
			TCPIP_HTTP_Print_BattAlmType(connHandle,3);
			break;
        case 0x000000f3:
			TCPIP_HTTP_Print_bckbatteryTh(connHandle);
			break;
        case 0x000000f4:
			TCPIP_HTTP_Print_config_bckbattchecked(connHandle);
			break;
        case 0x000000f5:
			TCPIP_HTTP_Print_BckBattAlmType(connHandle,1);
			break;
        case 0x000000f6:
			TCPIP_HTTP_Print_BckBattAlmType(connHandle,2);
			break;
        case 0x000000f7:
			TCPIP_HTTP_Print_BckBattAlmType(connHandle,3);
			break;
        case 0x000000f8:
			TCPIP_HTTP_Print_config_tprchecked(connHandle);
			break;
        case 0x000000f9:
			TCPIP_HTTP_Print_TprAlmType(connHandle,1);
			break;
        case 0x000000fa:
			TCPIP_HTTP_Print_TprAlmType(connHandle,2);
			break;
        case 0x000000fb:
			TCPIP_HTTP_Print_TprAlmType(connHandle,3);
			break;
        case 0x00000105:
			TCPIP_HTTP_Print_config_waterchecked(connHandle);
			break;
        case 0x00000106:
			TCPIP_HTTP_Print_WtrAlmType(connHandle,1);
			break;
        case 0x00000107:
			TCPIP_HTTP_Print_WtrAlmType(connHandle,2);
			break;
        case 0x00000108:
			TCPIP_HTTP_Print_WtrAlmType(connHandle,3);
			break;
        case 0x00000112:
			TCPIP_HTTP_Print_config_adcchecked(connHandle);
			break;
        case 0x00000113:
			TCPIP_HTTP_Print_ADCAlmType(connHandle,1);
			break;
        case 0x00000114:
			TCPIP_HTTP_Print_ADCAlmType(connHandle,2);
			break;
        case 0x00000115:
			TCPIP_HTTP_Print_ADCSensorNone(connHandle);
			break;
        case 0x00000116:
			TCPIP_HTTP_Print_ADCSensorPIR(connHandle);
			break;
        case 0x00000120:
			TCPIP_HTTP_Print_config_drychecked(connHandle,0);
			break;
        case 0x00000121:
			TCPIP_HTTP_Print_Dry1AlmType1(connHandle);
			break;
        case 0x00000122:
			TCPIP_HTTP_Print_Dry1AlmType2(connHandle);
			break;
        case 0x00000123:
			TCPIP_HTTP_Print_notify_dry_clear(connHandle,0);
			break;
        case 0x00000124:
			TCPIP_HTTP_Print_Dry1Sensor(connHandle,0);
			break;
        case 0x00000125:
			TCPIP_HTTP_Print_Dry1Sensor(connHandle,1);
			break;
        case 0x00000126:
			TCPIP_HTTP_Print_Dry1Sensor(connHandle,2);
			break;
        case 0x00000130:
			TCPIP_HTTP_Print_config_drychecked(connHandle,1);
			break;
        case 0x00000131:
			TCPIP_HTTP_Print_Dry2AlmType1(connHandle);
			break;
        case 0x00000132:
			TCPIP_HTTP_Print_Dry2AlmType2(connHandle);
			break;
        case 0x00000133:
			TCPIP_HTTP_Print_notify_dry_clear(connHandle,1);
			break;
        case 0x00000134:
			TCPIP_HTTP_Print_Dry2Sensor(connHandle,0);
			break;
        case 0x00000135:
			TCPIP_HTTP_Print_Dry2Sensor(connHandle,1);
			break;
        case 0x00000136:
			TCPIP_HTTP_Print_Dry2Sensor(connHandle,2);
			break;
        case 0x00000140:
			TCPIP_HTTP_Print_config_drychecked(connHandle,2);
			break;
        case 0x00000141:
			TCPIP_HTTP_Print_Dry3AlmType1(connHandle);
			break;
        case 0x00000142:
			TCPIP_HTTP_Print_Dry3AlmType2(connHandle);
			break;
        case 0x00000143:
			TCPIP_HTTP_Print_notify_dry_clear(connHandle,2);
			break;
        case 0x00000144:
			TCPIP_HTTP_Print_Dry3Sensor(connHandle,0);
			break;
        case 0x00000145:
			TCPIP_HTTP_Print_Dry3Sensor(connHandle,1);
			break;
        case 0x00000146:
			TCPIP_HTTP_Print_Dry3Sensor(connHandle,2);
			break;
        case 0x00000150:
			TCPIP_HTTP_Print_config_drychecked(connHandle,3);
			break;
        case 0x00000151:
			TCPIP_HTTP_Print_Dry4AlmType1(connHandle);
			break;
        case 0x00000152:
			TCPIP_HTTP_Print_Dry4AlmType2(connHandle);
			break;
        case 0x00000153:
			TCPIP_HTTP_Print_notify_dry_clear(connHandle,3);
			break;
        case 0x00000154:
			TCPIP_HTTP_Print_Dry4Sensor(connHandle,0);
			break;
        case 0x00000155:
			TCPIP_HTTP_Print_Dry4Sensor(connHandle,1);
			break;
        case 0x00000156:
			TCPIP_HTTP_Print_Dry4Sensor(connHandle,2);
			break;
        case 0x00000160:
			TCPIP_HTTP_Print_status_ip(connHandle);
			break;
        case 0x00000161:
			TCPIP_HTTP_Print_Public_IPAddress(connHandle);
			break;
        case 0x00000162:
			TCPIP_HTTP_Print_new_wanip(connHandle);
			break;
        case 0x00000163:
			TCPIP_HTTP_Print_old_wanip(connHandle);
			break;
		default:
			// Output notification for undefined values
                       sktHTTP = TCPIP_HTTP_CurrentConnectionSocketGet(connHandle);
			TCPIP_TCP_ArrayPut(sktHTTP, (const uint8_t*)"!DEF", 4);
	}

	return;
}

void TCPIP_HTTP_Print_(HTTP_CONN_HANDLE connHandle)
{
       TCP_SOCKET sktHTTP = TCPIP_HTTP_CurrentConnectionSocketGet(connHandle);
	TCPIP_TCP_Put(sktHTTP, '~');
	return;
}

